"""empty message

Revision ID: 49d884061e97
Revises: 0a095b443254
Create Date: 2024-07-22 01:23:48.177216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49d884061e97'
down_revision: Union[str, None] = '0a095b443254'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Book', schema=None) as batch_op:
        batch_op.alter_column('edition_date',
               existing_type=sa.DATE(),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Book', schema=None) as batch_op:
        batch_op.alter_column('edition_date',
               existing_type=sa.Integer(),
               type_=sa.DATE(),
               existing_nullable=True)

    # ### end Alembic commands ###
